name: merkant
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^5.0.3
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  animated_bottom_navigation_bar: ^1.3.3
  material_design_icons_flutter: ^7.0.7296
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  dio: ^5.7.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.8.0
  flare_flutter: ^3.0.2
  animated_snack_bar: ^0.4.0
  badges: ^3.1.2
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  string_validator: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  curved_progress_bar: ^1.0.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  flutter_slidable: ^3.1.1
  qr_code_scanner: ^1.0.1
  barcode: ^2.2.8
  flutter_svg: ^2.0.14
  flutter_typeahead: ^5.2.0
  window_manager: ^0.4.3
  wolt_modal_sheet: ^0.9.3
  brasil_fields: ^1.15.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  shimmer: ^3.0.0
  package_info_plus: ^8.1.1
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  modular_test:

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.png"
  image_path_ios: "assets/appicon_ios.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/appicon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/appicon.png"
    icon_size: 100 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/appicon.png"
